
# Reverse correlation analysis

```{r setup, include = FALSE}

library('groundhog')
groundhog.library(
  c(
    'papaja',
    'reticulate',
    'tidyverse',
    'broom',
    'estimatr', #for robust regression
    'cowplot',
    'MESS', # for AUCs
    'lsr', # for effect sizes
    'pwr', # for power calculations
    'brms', # for mixed effects modeling
    'BayesFactor',# for Bayesian t test
    'jsonlite', #parsing data from sort_trial
    'afex' #for anova
  ), "2022-12-01"
)
r_refs("r-references.bib")

```

# Load data

```{r load_and_format_data, echo=FALSE, cache=TRUE}

E1.frames_df <- read_csv('../experiments/Exp1pixels/version2/data/jatos_resultfiles_batch1/all_data.csv') %>%
  mutate(subj_id=PROLIFIC_PID,
         correct = as.numeric(correct),
         RT = as.numeric(RT),
         present=factor(as.numeric(present),levels=c(1,0)),
         resp = response==presence_key,
         correlation_with_mask=as.numeric(correlation_with_mask)) %>%
  filter(test_part %in% c('test1','test2'))%>%
  mutate(p=ifelse(present==0,0,max_p))%>%
  group_by(p, hide_proportion)%>%
  mutate(correlation_with_target_letter_corrected = 
           correlation_with_target_letter-mean(correlation_with_target_letter, na.rm=T),
         occlusion=factor(ifelse(hide_proportion<0.10,'low','high')))

E2.frames_df <- read_csv('../experiments/Exp2rows/data/jatos_resultfiles_batch1/all_data_with_SSE.csv') %>%
  mutate(subj_id=PROLIFIC_PID,
         correct = as.numeric(correct),
         RT = as.numeric(RT),
         present=factor(as.numeric(present),
                        levels=c(1,0)),
         resp = response==presence_key)  %>%
  filter(test_part %in% c('test1','test2'))%>%
  mutate(p=ifelse(present==0,0,max_p))%>%
  group_by(p, hide_proportion)%>%
  mutate(correlation_with_target_letter_corrected = 
           correlation_with_target_letter-mean(correlation_with_target_letter, na.rm=T),
         correlation_with_other_letter_corrected = 
           correlation_with_other_letter-mean(correlation_with_other_letter, na.rm=T),
         occlusion=factor(ifelse(hide_proportion<0.2,'low','high')))


E3.frames_df <- read_csv('../experiments/Exp3reference/data/jatos_results_files_batch1/all_data.csv') %>%
  mutate(subj_id=PROLIFIC_PID,
         correct = as.numeric(correct),
         RT = as.numeric(RT),
         present=factor(as.numeric(present),levels=c(1,0)),
         resp = response==presence_key) %>%
  filter(test_part %in% c('test1','test2'))%>%
  mutate(p=ifelse(present==0,0,max_p))%>%
  group_by(p, hide_proportion)%>%
  mutate(correlation_with_target_letter_corrected = 
           correlation_with_target_letter-mean(correlation_with_target_letter, na.rm=T),
         occlusion=factor(ifelse(hide_proportion<0.2,'low','high')))

E2a.frames_df <- read_csv('../experiments/Exp2rowsLong/data/json_data/all_data.csv') %>%
  mutate(subj_id=PROLIFIC_PID,
         correct = as.numeric(correct),
         RT = as.numeric(RT),
         present=factor(as.numeric(present),levels=c(1,0)),
         resp = response==presence_key,
         trial_index=subject_identifier+trial_index)%>%
  filter(test_part %in% c('test1','test2'))%>%
  mutate(p=ifelse(present==0,0,max_p))%>%
  group_by(p, hide_proportion)%>%
  mutate(correlation_with_target_letter_corrected = 
           correlation_with_target_letter-mean(correlation_with_target_letter, na.rm=T),
         occlusion=factor(ifelse(hide_proportion<0.2,'low','high')))


```

Plotting the correlation between the presented frame and the target as a function of target presence. This is a sanity check to make sure the correlation is higher in target-present trials.

```{r plot_correlation, echo=FALSE, cache=TRUE}


E1.frames_df %>%
  filter(test_part %in% c('test1','test2'))%>%
  filter(RT>2000)%>% # to minimize effects of selection bias
  mutate(present = factor(present, levels=c(0,1), labels=c('absent','present'))) %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter, na.rm=T),
            se = se(correlation_with_target_letter, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation', title='Exp. 3') +
  theme_classic()

ggsave('../docs/figures/RC/visibility_by_presence_E1.png', width=4,height=3)

E2.frames_df %>%
  filter(test_part %in% c('test1','test2'))%>%
  filter(RT>2000)%>% # to minimize effects of selection bias
  mutate(present = factor(present, levels=c(0,1), labels=c('absent','present'))) %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter, na.rm=T),
            se = se(correlation_with_target_letter, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation', title='Exp. 4') +
  theme_classic()

ggsave('../docs/figures/RC/visibility_by_presence_E2.png', width=4,height=3)

E2a.frames_df %>%
  filter(test_part %in% c('test1','test2'))%>%
  mutate(present = factor(present, levels=c(0,1), labels=c('absent','present'))) %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter, na.rm=T),
            se = se(correlation_with_target_letter, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation', title='Exp. 4') +
  theme_classic()

ggsave('../docs/figures/RC/visibility_by_presence_E2a.png', width=4,height=3)


```

```{r SSE, echo=FALSE, cache=TRUE}


# E1.frames_df %>%
#   filter(test_part %in% c('test1','test2'))%>%
#   filter(RT>2000)%>% # to minimize effects of selection bias
#   mutate(present = factor(present, levels=c(0,1), labels=c('absent','present'))) %>%
#   group_by(present,frame_index)%>%
#   summarise(r=mean(correlation_with_target_letter, na.rm=T),
#             se = se(correlation_with_target_letter, na.rm=T)) %>%
#   filter(frame_index<100) %>%
#   ggplot(aes(x=frame_index,y=r,color=present)) +
#   geom_line(size=1) + 
#   geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
#   labs(x = 'frame index', y = 'correlation', title='Exp. 3') +
#   theme_classic()

# ggsave('../docs/figures/RC/visibility_by_presence_E1.png', width=4,height=3)
# 
# E2.frames_df %>%
#   filter(test_part %in% c('test1','test2'))%>%
#   filter(RT>2000)%>% # to minimize effects of selection bias
#   mutate(present = factor(present, levels=c(0,1), labels=c('absent','present'))) %>%
#   group_by(present,frame_index)%>%
#   summarise(SSE=mean(SSE_with_target_letter, na.rm=T),
#             se = se(SSE_with_target_letter, na.rm=T)) %>%
#   filter(frame_index<100) %>%
#   ggplot(aes(x=frame_index,y=SSE,color=present)) +
#   geom_line(size=1) + 
#   geom_ribbon(aes(ymin=SSE-se, ymax=SSE+se, fill=present), alpha=0.5) +
#   labs(x = 'frame index', y = 'SSE', title='Exp. 4') +
#   theme_classic()
# 
# ggsave('../docs/figures/RC/visibility_by_presence_E2.png', width=4,height=3)
# 
# E2a.frames_df %>%
#   filter(test_part %in% c('test1','test2'))%>%
#   mutate(present = factor(present, levels=c(0,1), labels=c('absent','present'))) %>%
#   group_by(present,frame_index)%>%
#   summarise(r=mean(correlation_with_target_letter, na.rm=T),
#             se = se(correlation_with_target_letter, na.rm=T)) %>%
#   filter(frame_index<100) %>%
#   ggplot(aes(x=frame_index,y=r,color=present)) +
#   geom_line(size=1) + 
#   geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
#   labs(x = 'frame index', y = 'correlation', title='Exp. 4') +
#   theme_classic()
# 
# ggsave('../docs/figures/RC/visibility_by_presence_E2a.png', width=4,height=3)


```

Mean-centering correlations for the reverse correlation analysis. 

```{r mean-center-correlations, echo=FALSE, cache=TRUE}



E1.frames_df %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter_corrected, na.rm=T),
            se = se(correlation_with_target_letter_corrected, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation corrected', title='Exp. 1') +
  theme_classic()

ggsave('../docs/figures/RC/visibility_by_presence_corrected_E1.png', width=4,height=3)



E2.frames_df %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter_corrected, na.rm=T),
            se = se(correlation_with_target_letter_corrected, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation corrected', title='Exp. 1') +
  theme_classic()

ggsave('../docs/figures/RC/visibility_by_presence_corrected_E2.png', width=4,height=3)


E2a.frames_df %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter_corrected, na.rm=T),
            se = se(correlation_with_target_letter_corrected, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation corrected', title='Exp. 2') +
  theme_classic()

ggsave('../docs/figures/RC/visibility_by_presence_corrected_E2a.png', width=4,height=3)

E3.frames_df %>%
  group_by(present,frame_index)%>%
  summarise(r=mean(correlation_with_target_letter_corrected, na.rm=T),
            se = se(correlation_with_target_letter_corrected, na.rm=T)) %>%
  filter(frame_index<100) %>%
  ggplot(aes(x=frame_index,y=r,color=present)) +
  geom_line(size=1) + 
  geom_ribbon(aes(ymin=r-se, ymax=r+se, fill=present), alpha=0.5) +
  labs(x = 'frame index', y = 'correlation corrected', title='Exp. 2') +
  theme_classic()


ggsave('../docs/figures/RC/visibility_by_presence_corrected_E3.png', width=4,height=3)

```

Plotting decision kernels: 

```{r reverse_correlation, echo=FALSE, cache=TRUE}


E1.frames_df %>%
  filter(frame_index<25)%>%
  group_by(subj_id,frame_index,occlusion) %>%
  summarise(decision=mean(correlation_with_target_letter_corrected[resp])-
                            mean(correlation_with_target_letter_corrected[!resp])) %>%
  group_by(frame_index) %>%
  summarise(se = se(decision, na.rm=T),
            decision=mean(decision, na.rm=T)) %>%
  ggplot(aes(x=frame_index,y=decision,ymin=decision-se,ymax=decision+se)) +
  geom_abline(intercept=0,slope=0, color='black')+
  geom_line(size=1) +
  geom_ribbon(alpha=0.5) +
  labs(x='frame index', y='decision contrast',title='Exp.3')+
  theme_classic()

ggsave('../docs/figures/RC/decision_kernel_E1.png', width=4,height=3)

E2.frames_df  %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>=0 & time<1000)%>%
  pivot_longer(
    cols = c(correlation_with_target_letter_corrected, correlation_with_other_letter_corrected),
    names_to = "reference",
    values_to = "correlation"
  )%>%
  mutate(reference = ifelse(reference=="correlation_with_target_letter_corrected","target","other"))%>%
  group_by(subj_id,time,occlusion,reference) %>%
  summarise(decision=mean(correlation[resp])-
                            mean(correlation[!resp])) %>%
  group_by(time,reference) %>%
  summarise(se = se(decision, na.rm=T),
            decision=mean(decision, na.rm=T)) %>%
  ggplot(aes(x=time,y=decision,ymin=decision-se,ymax=decision+se, color=reference,fill=reference)) +
  geom_abline(intercept=0,slope=0)+
  geom_line(size=1) +
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_ribbon(alpha=0.5) +
  labs(x='time (ms)', y='decision contrast',title='Decision kernel')+
  theme_classic()

ggsave('../docs/figures/RC/decision_kernel_with_other_E2.png', width=4,height=3)

E2.frames_df  %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>=0 & time<1000)%>%
  group_by(subj_id,time,occlusion) %>%
  summarise(decision=mean(correlation_with_target_letter_corrected[resp])-
                            mean(correlation_with_target_letter_corrected[!resp])) %>%
  group_by(time) %>%
  summarise(se = se(decision, na.rm=T),
            decision=mean(decision, na.rm=T)) %>%
  ggplot(aes(x=time,y=decision,ymin=decision-se,ymax=decision+se)) +
  geom_abline(intercept=0,slope=0)+
  geom_line(size=1) +
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_ribbon(alpha=0.5) +
  labs(x='time (ms)', y='decision contrast',title='Decision kernel')+
  theme_classic()

ggsave('../docs/figures/RC/decision_kernel_E2.png', width=4,height=3)

E2a.frames_df %>%
  filter(frame_index>7 & frame_index<25)%>%
  group_by(subj_id,frame_index,occlusion) %>%
  summarise(decision=mean(correlation_with_target_letter_corrected[resp])-
                            mean(correlation_with_target_letter_corrected[!resp])) %>%
  group_by(frame_index) %>%
  summarise(se = se(decision, na.rm=T),
            decision=mean(decision, na.rm=T)) %>%
  ggplot(aes(x=frame_index,y=decision,ymin=decision-se,ymax=decision+se)) +
  geom_abline(intercept=0,slope=0, color='black')+
  geom_line(size=1) +
  geom_ribbon(alpha=0.5) +
  labs(x='frame index', y='decision contrast',title='Exp.4')+
  theme_classic()

ggsave('../docs/figures/RC/decision_kernel_E2a.png', width=4,height=3)

```


```{r reverse_correlation_confidence, echo=FALSE, cache=TRUE}

E2.rc_confidence <- E2.frames_df %>%
  filter(frame_index>7 & frame_index<13 & correct & !is.na(confidence))%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            confidence=mean(confidence))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(confidence=cor(evidence,confidence,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(confidence=mean(confidence))%>%
  spread(present,confidence,sep='') %>%
  mutate(diff=present1+present0)

detection_colors = c('#377eb8', '#e41a1c');

p<- E2.frames_df %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>=0 & time<500 & correct & !is.na(confidence))%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(confidence=cor(correlation_with_target_letter_corrected,confidence,method='spearman')) %>%
  group_by(subj_id,present,time)%>%
  summarise(confidence=mean(confidence))%>%
  group_by(present,time)%>%
  summarise(se=se(confidence),
            confidence=mean(confidence, na.rm=T))%>%
  ggplot(aes(x=time,y=confidence,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=confidence-se,ymax=confidence+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="Confidence, Exp. 2") +
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E2confidence.png",p,width=4,height=3,dpi=600)

p<- E2.frames_df %>%
  mutate(time=frame_index*1000/15-533.33,
         present=factor(present,levels=c(1,0),labels=c('present','absent')))%>%
  filter(time>=0 & time<500 & correct & !is.na(confidence))%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(confidence=cor(correlation_with_target_letter_corrected,confidence,method='spearman')) %>%
  group_by(subj_id,present,time)%>%
  summarise(confidence=mean(confidence))%>%
  group_by(present,time)%>%
  summarise(se=se(confidence),
            confidence=mean(confidence, na.rm=T))%>%
  ggplot(aes(x=time,y=confidence,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=confidence-se,ymax=confidence+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="Confidence kernel") +
  facet_wrap(~present)+
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E2confidence_pivot.png",p,width=6,height=3,dpi=600)

p<- E2.frames_df %>%
  mutate(time=frame_index*1000/15-533.33,
         present=factor(present,levels=c(1,0),labels=c('present','absent')))%>%
  filter(time>=0 & time<300 & correct & !is.na(confidence))%>%
  group_by(subj_id,present,occlusion,confidence,trial_index) %>%
  summarise(correlation_with_target_letter_corrected=mean(correlation_with_target_letter_corrected))%>%
  group_by(subj_id,present,occlusion)%>%
  summarise(confidence=cor(correlation_with_target_letter_corrected,confidence,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(confidence=mean(confidence))%>%
  group_by(present)%>%
  summarise(se=se(confidence),
            confidence=mean(confidence, na.rm=T))%>%
  ggplot(aes(x=0,y=confidence,color=present,fill=present))+
  geom_abline(slope=0,intercept=0,color='black',size=1)+
  geom_errorbar(aes(ymin=confidence-se,ymax=confidence+se),width=0.2)+
  geom_point(size=6)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  scale_x_continuous(breaks=c(), limits=c(-1,1))+
  scale_y_continuous( limits=c(-0.15,0.15))+
  labs(x="", y="Spearman correlation", title="Confidence kernel") +
  facet_wrap(~present)+
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E2confidence_collapsed_pivot.png",p,width=6,height=3,dpi=600)

```

```{r reverse_correlation_RT, echo=FALSE, cache=TRUE}
E1.rc_RT <- E1.frames_df %>%
  filter(frame_index<6 & correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E1.rc_RT_inc <- E1.frames_df %>%
  filter(frame_index<6 & !correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E1.rc_acc <- E1.frames_df %>%
  filter(frame_index<6)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            correct=mean(correct))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(acc=mean(evidence[correct==1])-mean(evidence[correct==0])) %>%
  group_by(subj_id,present)%>%
  summarise(acc=mean(acc))%>%
  spread(present,acc,sep='') %>%
  mutate(diff=present1+present0)

p<- E1.frames_df %>%
  mutate(time=frame_index*1000/15)%>%
  filter(time<500 & correct)%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(RT=cor(correlation_with_target_letter_corrected,RT,method='spearman')) %>%
  group_by(subj_id,present,time)%>%
  summarise(RT=mean(RT))%>%
  group_by(present,time)%>%
  summarise(se=se(RT),
            RT=mean(RT, na.rm=T))%>%
  ggplot(aes(x=time,y=RT,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=RT-se,ymax=RT+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="RT, Exp. 1") +
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E1RT.png",p,width=4,height=3,dpi=600)

E1.rc_RT_mask <- E1.frames_df %>%
  filter(frame_index==1 & correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  mutate(evidence=correlation_with_mask)%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E2.rc_RT <- E2.frames_df %>%
  filter(frame_index>7 & frame_index<13 & correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E2.rc_RT_inc <- E2.frames_df %>%
  filter(frame_index>7 & frame_index<13 & !correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E2.rc_acc <- E2.frames_df %>%
  filter(frame_index>7 & frame_index<13)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            correct=mean(correct))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(acc=mean(evidence[correct==1])-mean(evidence[correct==0])) %>%
  group_by(subj_id,present)%>%
  summarise(acc=mean(acc))%>%
  spread(present,acc,sep='') %>%
  mutate(diff=present1+present0)

p<- E2.frames_df %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>0 & time<500 & correct)%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(RT=cor(correlation_with_target_letter_corrected,RT,method='spearman')) %>%
  group_by(subj_id,present,time)%>%
  summarise(RT=mean(RT))%>%
  group_by(present,time)%>%
  summarise(se=se(RT),
            RT=mean(RT, na.rm=T))%>%
  ggplot(aes(x=time,y=RT,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=RT-se,ymax=RT+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="RT, Exp. 2") +
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E2RT.png",p,width=4,height=3,dpi=600)

p<- E2.frames_df %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>0 & time<500 & correct)%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(RT=cor(correlation_with_target_letter_corrected,RT,method='spearman')) %>%
  mutate(present=factor(present, levels=c(1,0),labels=c('present','absent')))%>%
  group_by(subj_id,present,time)%>%
  summarise(RT=mean(RT))%>%
  group_by(present,time)%>%
  summarise(se=se(RT),
            RT=mean(RT, na.rm=T))%>%
  ggplot(aes(x=time,y=RT,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=RT-se,ymax=RT+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="Reaction time kernel") +
  theme_minimal() +
  theme(legend.pos='na')+
  facet_wrap(~present)

ggsave("../docs/figures/RC/E2RT_pivot.png",p,width=6,height=3,dpi=600)


p<- E2.frames_df %>%
  mutate(time=frame_index*1000/15-533.33,
         present=factor(present,levels=c(1,0),labels=c('present','absent')))%>%
  filter(time>=0 & time<300 & correct )%>%
  group_by(subj_id,present,occlusion,RT,trial_index) %>%
  summarise(correlation_with_target_letter_corrected=mean(correlation_with_target_letter_corrected))%>%
  group_by(subj_id,present,occlusion)%>%
  summarise(RT=cor(correlation_with_target_letter_corrected,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  group_by(present)%>%
  summarise(se=se(RT),
            RT=mean(RT, na.rm=T))%>%
  ggplot(aes(x=0,y=RT,color=present,fill=present))+
  geom_abline(slope=0,intercept=0,color='black',size=1)+
  geom_errorbar(aes(ymin=RT-se,ymax=RT+se),width=0.2)+
  geom_point(size=6)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  scale_x_continuous(breaks=c(), limits=c(-1,1))+
  scale_y_continuous( limits=c(-0.15,0.15))+
  labs(x="", y="Spearman correlation", title="Reaction time kernel") +
  facet_wrap(~present)+
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E2RT_collapsed_pivot.png",p,width=6,height=3,dpi=600)

E3.rc_RT <- E3.frames_df %>%
  filter(frame_index>7 & frame_index<13 & correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E3.rc_RT_inc <- E3.frames_df %>%
  filter(frame_index>7 & frame_index<13 & !correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E3.rc_acc <- E3.frames_df %>%
  filter(frame_index>7 & frame_index<13)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            correct=mean(correct))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(acc=mean(evidence[correct==1])-mean(evidence[correct==0])) %>%
  group_by(subj_id,present)%>%
  summarise(acc=mean(acc))%>%
  spread(present,acc,sep='') %>%
  mutate(diff=present1+present0)

p<- E3.frames_df %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>=0 & time<500 & correct)%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(RT=cor(correlation_with_target_letter_corrected,RT,method='spearman')) %>%
  group_by(subj_id,present,time)%>%
  summarise(RT=mean(RT))%>%
  group_by(present,time)%>%
  summarise(se=se(RT),
            RT=mean(RT, na.rm=T))%>%
  ggplot(aes(x=time,y=RT,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=RT-se,ymax=RT+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="RT, Exp. 3") +
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E3RT.png",p,width=4,height=3,dpi=600)

E2a.rc_RT <- E2a.frames_df %>%
  filter(frame_index>7 & frame_index<13 & correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E2a.rc_RT_inc <- E2a.frames_df %>%
  filter(frame_index>7 & frame_index<13 & !correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(RT=cor(evidence,RT,method='spearman')) %>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(RT))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)


E2a.rc_acc <- E2a.frames_df %>%
  filter(frame_index>7 & frame_index<13)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            correct=mean(correct))%>%
  group_by(subj_id,present,occlusion) %>%
  summarise(acc=mean(evidence[correct==1])-mean(evidence[correct==0])) %>%
  group_by(subj_id,present)%>%
  summarise(acc=mean(acc))%>%
  spread(present,acc,sep='') %>%
  mutate(diff=present1+present0)

p<- E2a.frames_df %>%
  mutate(time=frame_index*1000/15-533.33)%>%
  filter(time>=0 & time<500 & correct)%>%
  group_by(subj_id,present,occlusion,time) %>%
  summarise(RT=cor(correlation_with_target_letter_corrected,RT,method='spearman')) %>%
  group_by(subj_id,present,time)%>%
  summarise(RT=mean(RT))%>%
  group_by(present,time)%>%
  summarise(se=se(RT),
            RT=mean(RT, na.rm=T))%>%
  ggplot(aes(x=time,y=RT,color=present,fill=present))+
  geom_segment(aes(x=0,y=0,xend=300,yend=0),size=2, color='black')+
  geom_line(size=1)+
  geom_ribbon(aes(ymin=RT-se,ymax=RT+se),alpha=0.3)+
  scale_color_manual(values=detection_colors)+
  scale_fill_manual(values=detection_colors) +
  labs(x="time (ms)", y="Spearman correlation", title="RT, long Exp. 2") +
  theme_minimal() +
  theme(legend.pos='na')

ggsave("../docs/figures/RC/E2aRT.png",p,width=4,height=3,dpi=600)


```

```{r rc-confidence-beta, message=F, warning=F, echo=F, include=F}


E2.rc_confidence_lm <- E2.frames_df %>%
  filter(frame_index>7 & frame_index<13 & correct & !is.na(confidence))%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            confidence=mean(confidence))%>%
  group_by(subj_id,present,occlusion) %>%
  group_modify(~tidy(lm(confidence~evidence,data=.))) %>%
  filter(term=="evidence")%>%
  group_by(subj_id,present)%>%
  summarise(confidence=mean(estimate))%>%
  spread(present,confidence,sep='') %>%
  mutate(diff=present1+present0)


E2a.rc_RT_lm <- E2a.frames_df %>%
  filter(frame_index>7 & frame_index<13 & correct)%>%
  group_by(subj_id,trial_index,present,occlusion)%>%
  summarise(evidence=mean(correlation_with_target_letter_corrected),
            RT=mean(RT))%>%
  group_by(subj_id,present,occlusion) %>%
  group_modify(~tidy(lm_robust(RT~evidence,data=.))) %>%
  filter(term=="evidence")%>%
  group_by(subj_id,present)%>%
  summarise(RT=mean(estimate))%>%
  spread(present,RT,sep='') %>%
  mutate(diff=present1+present0)

E2.frames_df %>%
  filter(frame_index>7 & frame_index<40 & correct & !is.na(confidence))%>%
  group_by(subj_id,present,occlusion,frame_index) %>%
  summarise(confidence=cor(correlation_with_target_letter_corrected,confidence,method='spearman')) %>%
  group_by(subj_id,present,frame_index)%>%
  summarise(confidence=mean(confidence))%>%
  group_by(present,frame_index)%>%
  summarise(se=se(confidence),
            confidence=mean(confidence, na.rm=T))%>%
  ggplot(aes(x=frame_index,y=confidence,color=factor(present),fill=factor(present)))+
  geom_abline(slope=0,intercept=0)+
  geom_line()+
  geom_ribbon(aes(ymin=confidence-se,ymax=confidence+se),alpha=0.3)+
      scale_color_manual(values=detection_colors)+
    scale_fill_manual(values=detection_colors)
  
```